name: staging checks

on:
  workflow_call:
  
jobs:
  staging-checks:
    runs-on: ubuntu-latest
    name: Deploy staging, run tests (go lang & api tests)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Install serverless
        run: npm i -g serverless
      
      - name: Configure AWS Credentials for Testing (default)
        run: serverless config credentials 
          --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} 
          --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          --profile default

      - name: Configure AWS Credentials (staging)
        run: serverless config credentials 
          --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} 
          --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          --profile staging

      - name: Set up language dependencies
        run: npm run setup-lang-deps

      - name: Run golang tests
        run: npm run test

      - name: Download npm dependencies
        run: npm ci

      - name: Deploy to Staging
        run: npm run deploy:staging